pingcap/tipocket

.gitignore, Makefile, cmd/rawkv/main.go, cmd/tidb/main.go, cmd/txnkv/main.go, cmd/util/suit.go, cmd/verifier/main.go, db/cluster/cluster.go, db/rawkv/register.go, db/tidb/bank.go, db/tidb/long_fork.go, db/tidb/multi_bank.go, db/tidb/sequential.go, db/txnkv/register.go, go.sum, pkg/check/porcupine/porcupine.go, pkg/cluster/cluster.go, pkg/control/config.go, pkg/core/client.go, pkg/core/db.go, pkg/core/nemesis.go, pkg/model/cas_register_test.go, pkg/nemesis/generator.go, pkg/nemesis/nemesis.go, pkg/util/util.go
- ~~[ ] Refactor the `Nemesis` interface~~
To retain the backward compatibility, I extract out a `Node` struct and denotes a Pod on K8s environment.
That's means we cannot inject pod-kill kind faults using chaos-mesh currently, because they destroy the Pod and make the related `Node` be illegal. we need resolve this limitation in the future.
Tests 
Code changes
Side effects
```release-note
NONE
```
=> *: extract interface to be implemented

Dockerfile, pkg/cluster/k8s.go, pkg/test-infra/fixture/fixture.go, pkg/test-infra/tidb/operation.go, pkg/test-infra/tidb/recommend.go
Need to create a TiDB monitor when create the TiDB cluster.
On GKE, I found a problem that when I use LoadBalancer as the Grafana service type, the NodePort is always changing, and the Grafana dashboard isn't accessible. Maybe refs: https://github.com/pingcap/tidb-operator/issues/1949
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> k8s cluster: Support tidb monitor

pkg/test-infra/fixture/fixture.go, pkg/test-infra/tidb/operation.go
Be able to choose a configmap for tidb/tikv/pd cluster
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> support tidb/tikv/pd configmap as arguments

pkg/test-infra/abtest/recommand.go, pkg/test-infra/tidb/recommend.go
As per discuss offline, we need to limit the tikv and tidb failover count to 3.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> Add failover count limit

pkg/cluster/types/cluster.go, pkg/test-infra/tidb/operation.go
When we know the client clusterName, we can access other component through DNS address easily.
For example, on https://github.com/pingcap/tipocket/pull/112, we can build the PD address using clusterName and namespace name.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> *: add more information on clientNode

cmd/abtest/main.go, pkg/test-infra/fixture/abtest.go, pkg/test-infra/fixture/fixture.go
Add an argument to control a/b test concurrency.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> a/b test: add abtest concurrency argument

argo/template/abtest.yaml, argo/template/bank-iochaos.yaml, argo/template/bank.yaml, argo/template/binlog.yaml, argo/template/block-writer.yaml, argo/template/export-logs.yaml, argo/template/ledger.yaml, argo/template/region-available.yaml, argo/template/sqllogic.yaml, argo/template/tpcc.yaml, argo/template/txn-rand-pessimistic.yaml, argo/workflow/abtest-chunk-rpc.yaml, argo/workflow/abtest-plan-cache.yaml, argo/workflow/abtest-tmp-storage.yaml, argo/workflow/abtest.yaml, argo/workflow/bank-iochaos.yaml, argo/workflow/bank.yaml, argo/workflow/binlog.yaml, argo/workflow/block-writer.yaml, argo/workflow/ledger.yaml, argo/workflow/region-available.yaml, argo/workflow/sqllogic.yaml, argo/workflow/tpcc.yaml, argo/workflow/txn-rand-pessimistic.yaml
There is a bug in current workflow manifest. Template `call-export-logs` and template `call-tipocket-xxx` both has a `ns` parameter, so when trying to submit workflow via argo cli with parameter overwritten such as `-p ns=xxx`, the namespace won't change (not sure why). The solution for this is to make the input parameter global, so that each template can render that value as its input. 
This PR also does:
1. remove `retryStrategy`
2. make loki related parameters configurable
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
- Need to update the …
=> Refactor argo templates and workflows

pkg/pocket/core/check.go, pkg/pocket/core/core.go, pkg/pocket/core/execute.go
Currently there is a rarely happened bug, when the generator is locked, the SQL already generated may be executed. To fix this problem, this PR add a lock for executor, not the best way, but it works.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> pocket: fix pocket check while executing SQL

pkg/pocket/core/check.go
CDC requires tables to have pk or unique indexes
Add primary key when to create wait table
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> Add primary key when to create wait table

pkg/test-infra/tidb/recommend.go
Currently we set the version field in the tidbcluster CR.  But actually this introduces a bug in tidb-operator. Tidb operator uses the `baseImage` field instead of the `image` field when version is not `""`, so when we want to use the images from `hub.pingcap.net`, it won't work. So this PR removes the `version` field in tidbcluster CR.
``` go
// This function set baseimage to not "" when version is not "".
func setPdSpecDefault(tc *v1alpha1.TidbCluster) {
if len(tc.Spec.Version) > 0 || tc.Spec.PD.Version != nil {
if tc.Spec.PD.BaseImage == "" {
tc.Spec.PD.BaseImage = defaultPDImage
}
}
}
// This function overwrites the image.
func (tc *TidbCluster) PDImage() string {
image := tc.Spec.PD.Image
baseImage := tc.Spec.PD.BaseImage
// base image …
```
=> Remove version field in tidbcluster

argo/template/abtest.yaml, argo/template/binlog.yaml, argo/template/cdc.yaml, argo/template/sc_bank.yaml, argo/template/sc_bank2.yaml, argo/workflow/abtest-chunk-rpc.yaml, argo/workflow/abtest-plan-cache.yaml, argo/workflow/abtest-tmp-storage.yaml, argo/workflow/abtest.yaml, argo/workflow/binlog.yaml, argo/workflow/cdc.yaml, cmd/cdc-pocket/main.go, cmd/pocket/main.go, pkg/pocket/config/config.go, pkg/pocket/config/config_test.go, pkg/pocket/connection/connection.go, pkg/pocket/connection/exec.go, pkg/pocket/core/check.go, pkg/pocket/core/execute.go, pkg/pocket/core/prepare.go, pkg/pocket/pkg/types/sql.go, pkg/test-infra/fixture/binlog.go, pkg/test-infra/fixture/fixture.go
- Fix binlog workload, pocket should wait for database sync done before starting job
- Add timeout in each compare, default to 1 hour
- Add general log, sync timeout and concurrency parameters for binlog & cdc workflow
- Add concurrency parameter for abtest workflow
Tests 
Code changes
Side effects
- No
- No
```release-note
NONE
```
=> pocket: fix startup in binlog workload

util/util.go
Previously get/setTiDBReplicaRead fatals when it occur errors, that will terminate test.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> don't fatal when get/setTiDBReplicaRead failed

argo/template/abtest.yaml, argo/template/bank.yaml, argo/template/binlog.yaml, argo/template/block-writer.yaml, argo/template/cdc.yaml, argo/template/ledger.yaml, argo/template/rawkv-linearizability.yaml, argo/template/read-stress.yaml, argo/template/region-available.yaml, argo/template/sc_bank.yaml, argo/template/sc_bank2.yaml, argo/template/sqllogic.yaml, argo/template/tiflash.yaml, argo/template/tpcc.yaml, argo/template/txn-rand-pessimistic.yaml, argo/template/vbank.yaml
This pr exposes the namespace parameter to each case, so that Prometheus can collect the namespace info for each case, then we can achieve the logs link feature in Argo.
=> Add namespace metadata label to case pod

go.mod, go.sum, pkg/pocket/core/check.go, pkg/pocket/executor/abtest.go, pkg/pocket/util/util.go
When startCheckConsistency occurred an error, it will fatal immediately, that't not what we expect.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> retry when abtest compare occurred an error

pkg/pocket/core/check.go
When some chaos injected, it's possible occur an error when closing db.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> degrade log level when compareExecutor close failed

pkg/control/control.go, pkg/nemesis/kill.go, pkg/test-infra/binlog/operation.go, pkg/test-infra/cdc/operation.go, pkg/test-infra/tidb/operation.go, pkg/test-infra/tiflash/operation.go, pkg/test-infra/util/util.go
tidb-server pod has multiple containers, and the `tidb` container isn't always the first one, sometimes we may see such logs when we set port incorrectly.
```
recover nemesis type:time-chaos,duration:1m48s,node:tipocket-vbank-tidb-0 172.31.10.70:0,...
```
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> Cluster: fix incorrect node port finding

pkg/control/control.go
On CDC tests, there exist two clientNodes, upstream tidb server and downstream tidb server.
So Tipocket will create two Clients, that will occur a panic when another client try to create `pocket` database.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> fix more clients problem on ModeSelfScheduled mode

argo/cron/bank.yaml, argo/cron/ledger.yaml, argo/cron/sc_bank.yaml, argo/cron/sc_bank2.yaml, argo/cron/vbank.yaml, argo/workflow/abtest-chunk-rpc.yaml, argo/workflow/abtest-plan-cache.yaml, argo/workflow/abtest-tmp-storage.yaml, argo/workflow/abtest.yaml, argo/workflow/bank-iochaos.yaml, argo/workflow/binlog.yaml, argo/workflow/block-writer.yaml, argo/workflow/cdc.yaml, argo/workflow/rawkv-linearizability.yaml, argo/workflow/read-stress-unify-all.yaml, argo/workflow/region-available.yaml, argo/workflow/sqllogic.yaml, argo/workflow/tiflash-abtest.yaml, argo/workflow/tiflash-cdc.yaml, argo/workflow/tiflash.yaml, argo/workflow/tpcc.yaml, argo/workflow/txn-rand-pessimistic.yaml, pkg/control/control.go, pkg/test-infra/tidb/recommend.go
This bug is fixed in the tidb-operator side, so we don't need to explicitly enable this anymore.
This PR also adds some missing part to argo yaml files
=> Add loki parameters to argo yaml files

pkg/control/control.go
```
fatal error: concurrent map read and map write
goroutine 1302 [running]:
runtime.throw(0x1eed8ea, 0x21)
/usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc001205cc0 sp=0xc001205c90 pc=0x42f5c2
runtime.mapaccess1_faststr(0x1bca0e0, 0xc000580900, 0xc000809980, 0x25, 0x6e)
/usr/local/go/src/runtime/map_faststr.go:21 +0x44f fp=0xc001205d30 sp=0xc001205cc0 pc=0x412c0f
github.com/pingcap/tipocket/pkg/control.(*Controller).fetchTiDBClusterLogs.func1(0xc000da2ea0, 0xc00025c460, 0xbfa2cc1b4d540d63, 0x2d155307fd, 0x32bc220, 0xc000efc3c0, 0x13, 0xc000809980, 0x25, 0xc000e6d190, ...)
/src/pkg/control/control.go:576 +0x3b9 fp=0xc001205f88 sp=0xc001205d30 pc=0x182b399
runtime.goexit()
/usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc001205f90 …
```
=> loki: fix concurrency map read and write problem

pkg/pocket/executor/common.go
10s seems too short, which makes the test case flaky
=> Extend the tiflash sync wait time

argo/cron/cdc-kafka-normal.yaml, argo/cron/cdc-kafka.yaml, argo/cron/cdc-normal.yaml, argo/cron/cdc.yaml, argo/template/cdc.yaml, argo/workflow/cdc.yaml, pkg/test-infra/cdc/recommend.go, pkg/test-infra/fixture/cdc.go, pkg/test-infra/fixture/fixture.go
The consumer image has been pushed to `docker.io/pingcap/ticdc-kafka:nightly`, which is not compatible with the current repo we use. So this PR adds a flag to customized the image.
=> Add cdc kafka consumer image flag

argo/workflow/encryption/bank-tikv-encryption.yaml, argo/workflow/encryption/bank2-tikv-encryption.yaml, argo/workflow/encryption/tiflash-tikv-encryption.yaml, argo/workflow/encryption/tpcc-tikv-encryption.yaml
Signed-off-by: Yi Wu <yiwu@pingcap.com>
IO error will cause tikv panic (expected behavior) and tipocket case failure. Update encryption tests's nemesis to use `delay_tikv` instead
change encryption tests' nemesis to use `delay_tikv` instead of `mixed_tikv`.
no
=> Enc nemesis

pkg/test-infra/tidb/template.go
Sees:  https://github.com/tikv/tikv/pull/7944
Because of lack of `advertise-status-addr`, tikv-server uses status-addr as the fallback, and its value is set to "0.0.0.0:20180" which causes a panic when starts the tikv-server.
BTW, I don't know when will https://github.com/tikv/tikv/pull/7944 merge into release-4.0, so this PR will make it fail when testing on release-4.0 TiDB-cluster.
```log
[2020/06/04 03:33:03.085 +00:00] [INFO] [config.rs:202] ["no advertise-status-addr is specified, falling back to status-addr"] [status-addr=0.0.0.0:20180]
[2020/06/04 03:33:03.085 +00:00] [FATAL] [setup.rs:204] ["invalid configuration: \"[src/server/config.rs:209]: invalid advertise-status-addr: \\\"0.0.0.0:20180\\\"\""]
```
Tests 
- Unit test
- E2E test …
=> Fix: invalid advertise-status-addr

go.mod, pkg/control/control.go, pkg/core/nemesis.go, pkg/nemesis/kill.go
There is a bug in the previous PR: https://github.com/pingcap/tipocket/pull/262, because there uses a channel to trigger the recovery of nemesis, only one nemesis maybe recover, and another nemesis is pending forever.
Here is a simple demo showing how to control nemesis in test client:
```go
func (c *Case) Start(ctx context.Context, cfg interface{}, clientNodes []types.ClientNode) error {
control := ctx.Value("control").(*control.Controller)
for i := 1; i <= 3; i++ {
killGenerator, nemesisControl := nemesis.NewCoordinationKillGenerator(c.nodes[0:i])
control.UpdateNemesisGenerators(core.NewOneRoundNemesisGenerators(killGenerator))
// Start blocks until nemesis is prepared to start
nemesisControl.Start(ctx)
log.Info("nemesis starts")
time.Sleep(5 * time.Minute)
log.Info("5 minutes …
```
=> Fix: support controlling nemesis on client

pkg/test-infra/fixture/fixture.go, pkg/test-infra/util/util.go
The hub address for components can be used for testing an edited component with others default component such as from docker.io.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> Add hub args for components

README.md, go.mod, go.sum, pkg/test-infra/tidb/template.go
Add --advertise-address flag and update TiDB-operator version.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> Fix tidb --advertise-address issue

pkg/pocket/core/check.go
Fix the duplicate unlock lock issue. Because there exists a defer function, so I remove the unlock statements.
``` go
defer func() {
log.Info("free lock")
c.Unlock()
c.execMutex.Unlock()
}()
```
```
2020/06/23 12:00:10 check.go:191: [info] free lock 
fatal error: sync: unlock of unlocked mutex
goroutine 1741187 [running]:
runtime.throw(0x298b621, 0x1e)
/usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc002575b20 sp=0xc002575af0 pc=0x4313d2
sync.throw(0x298b621, 0x1e)
/usr/local/go/src/runtime/panic.go:760 +0x35 fp=0xc002575b40 sp=0xc002575b20 pc=0x431355
sync.(*Mutex).unlockSlow(0xc000282058, 0xc0ffffffff)
/usr/local/go/src/sync/mutex.go:196 +0xd6 fp=0xc002575b68 sp=0xc002575b40 pc=0x46ffe6
sync.(*Mutex).Unlock(...) …
```
=> Fix: remove duplicate unlock

pkg/test-infra/tidb/template.go
PR https://github.com/pingcap/tipocket/pull/265 causes unknown flag errors on the old release version. 
And https://github.com/tikv/tikv/pull/8016 make tikv-server won't panic when `advertise-status-addr` isn't specified, so we can remove this flag on tikv_start_script_template.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> fix unknown flag on old release version

argo/cron/cdc-file-sort.yaml
Fix metadata name conflict
use `tipocket-cdc-file-sort` in file sort test
Tests 
- Unit test
- E2E test
- release-note
NONE
=> fix metadata name in cdc file sort test

tests/list_append/append.go, tests/rw_register/register.go
When a transaction failed after some successful operations, it should be rollbacked, otherwise some keys will be permanently locked.
Rollback transactions when it got failed.
Code changes
Side effects
- No
- No
```release-note
NONE
```
=> elle: fix lock some keys on failed txn

pkg/cluster/manager/apiserver/artifact.go, pkg/cluster/manager/apiserver/workload.go, pkg/cluster/manager/artifacts/monitor.go, pkg/cluster/manager/types/workload.go, pkg/cluster/manager/util/docker.go, pkg/cluster/manager/workload/executor.go
This PR:
* inject artifact URL into workload containers
* Tear down when errors occurred
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> Apiserver: inject artifact URL into workload containers and add tearDown

pkg/cluster/manager/types/resource.go, pkg/nemesis/container_kill.go, pkg/nemesis/iochaos.go, pkg/nemesis/kill.go, pkg/nemesis/time_chaos.go, pkg/test-infra/scheme/scheme.go, tests/list_append/append.go, tests/rw_register/register.go
There are some invalid connection errors in commit stage, but actually we don't know whether this statement is executed successful or not. Currently we mark these transactions as failed, this may wrongly result to G1a phenomenon if the transactions are successfully committed. 
If the commit error is invalid connection error, we mark this transaction to unknown state.
Tests 
Code changes
Side effects
- This change may miss some real G1a phenomenon.
- None
=> elle: mark invalid connection in commit as unknown state

argo/cron/async-bank2.yaml, argo/cron/async-tpcc.yaml, argo/template/sc_bank2.yaml, argo/template/tpcc.yaml, cmd/bank2/main.go, cmd/tpcc/main.go, config/tidb/enable-async-commit.toml, db/tidb/tpcc.go, tests/bank2/bank2.go
Since pingcap/tidb#21365, async commit needs to be enabled by setting a system variable. So we need to change some cases.
Add `async-commit` and `one-pc` parameters to the `bank2` and `tpcc` cases, and set corresponding system variables in the `SetUp`.
Tests 
- Manual test: manually test if these cases successfully set the system variables
Code changes
```release-note
NONE
```
=> Add async commit and 1PC parameters for some cases

pkg/test-infra/fixture/fixture.go
Signed-off-by: Weiwen Chen <chenweiwen@pingcap.com>
[集群监控 grafana service 类型默认使用 NodePort #332](https://github.com/pingcap/tipocket/issues/332)
Change default value of TiDBMonitorSvcType to NodePort.
Tests 
- Unit test
Code changes
Side effects
```release-note
NONE
```
=> Change default value of TiDBMonitorSvcType to NodePort.

pkg/core/db.go, pkg/test-infra/fixture/fixture.go, pkg/test-infra/tidb/operation.go
Sometimes we need to set some global variables or do some other preparations to the TiDB cluster. With this PR, we can pass these preparation SQLs through arguments.
```release-note
NONE
```
=> Support run preparation sqls for TiDB clusters

pkg/test-infra/binlog/recommend.go, pkg/test-infra/binlog/template.go
This PR updates drainer-config and startup script making it compatible with the new version of drainer.
Uses test_infra.NewBinlogCluster to create a binlog testing cluster, for example, here is the demo:
https://github.com/pingcap/tipocket/blob/ddd23d16aa31b2ba84ef1dbb336a118ad8a88c36/cmd/pocket/main.go#L49-L61
Tests 
Code changes
Side effects
```release-note
NONE
```
=> test-infra: update the binlog support

pkg/test-infra/tidb/recommend.go, pkg/test-infra/tidb/template.go
Since the TiDB-Operator has supported mounting PV into containers, this PR updates recommend TiDB ops configuration with a log PV binding with TiDB container and save all main component log into PVs.
Tests 
Code changes
Side effects
```release-note
NONE
```
=> feat: support log volume binding

Makefile, argo/cron/async-bank2.yaml, argo/cron/async-tpcc.yaml, argo/template/sc_bank2.yaml, argo/template/tpcc.yaml, cmd/bank2/main.go, cmd/tpcc/main.go, db/tidb/tpcc.go, pkg/core/db.go, testcase/ondup/Makefile, testcase/rawkv-linearizability/Makefile, testcase/resolve-lock/Makefile, testcase/sqllogictest/Makefile, testcase/titan/Makefile, tests/bank2/bank2.go
I don't know why TiDB is blocked on empty exec statements: https://github.com/pingcap/tidb/issues/22646
```
2021/02/01 04:09:12 suit.go:87: [info] deploy cluster success, node:[tipocket-rw-register-v4011-pre-pd-0 172.18.42.40:2379 tipocket-rw-register-v4011-pre-pd-1 172.18.240.163:2379
tipocket-rw-register-v4011-pre-pd-2 172.18.180.156:2379 tipocket-rw-register-v4011-pre-tidb-0 172.18.201.168:4000 tipocket-rw-register-v4011-pre-tidb-1 172.18.42.56:4000 tipocket-
rw-register-v4011-pre-tikv-0 172.18.108.204:20160 tipocket-rw-register-v4011-pre-tikv-1 172.18.201.145:20160 tipocket-rw-register-v4011-pre-tikv-2 172.18.49.16:20160 tipocket-rw-r
egister-v4011-pre-tikv-3 172.18.172.100:20160], client node:[tipocket-rw-register-v4011-pre …
```
=> db: ignore the empty prepareSQL when set up DB

cmd/vbank/main.go, run/lib/case.libsonnet, run/workflow/vbank.jsonnet, tests/vbank/v_bank.go
1. `Client.idValue` should always return 0 when in multi-table mode.
2. Since `from` can be equal to `to` in vbank, `BankState.transfer` didn't handle it correctly.
Fix above issues, also allow specifying cluster name by command flag.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> tests/vbank: fix some bugs

cmd/vbank/main.go, run/lib/case.libsonnet, run/workflow/vbank.jsonnet, tests/vbank/v_bank.go
Cannot specify connection parameters currently.
Add a flag to allow us set connection parameters so that we can enable some new features (like async-commit, clustered index) by system variables, (eg. `-conn_params='tidb_enable_async_commit=1&tidb_enable_1pc=1'`)
Tests 
Code changes
Side effects
- None
- None
```release-note
NONE
```
=> tests/vbank: add a flag to set conn params

tests/vbank/v_bank.go
When vbank try to dump state in multi-table mode, there is a chance that the function will return ErrNoRows unexpectly, which causes the test failed with `[fatal] dump state failed, timed out waiting for the condition`.
Avoid ErrNoRows returned accidentally.
Tests 
Code changes
Side effects
- None
- None
```release-note
NONE
```
=> tests/vbank: fix unexpected error returned by invokeReadMultiTable

cmd/cdc-bank/main.go, pkg/cluster/cluster.go, pkg/test-infra/cdc/operation.go, pkg/test-infra/cdc/recommend.go, pkg/test-infra/clusters.go, pkg/test-infra/fixture/cdc.go, pkg/test-infra/fixture/fixture.go, pkg/test-infra/tidb/operation.go, pkg/test-infra/tidb/recommend.go, pkg/test-infra/util/util.go
This PR replaces deployment with tidb-operator and update monitor-initializer.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> cdc: replace deployment with tidb-operator and update monitor-initializer

cmd/backup/main.go, cmd/crud/main.go, cmd/follower-read/main.go, cmd/pbank/main.go, cmd/region-available/main.go, cmd/tpcc/main.go, pkg/test-infra/clusters.go, pkg/test-infra/fixture/fixture.go, run/lib/case.libsonnet, run/lib/config.libsonnet, run/workflow/vbank.jsonnet, testcase/bank/cmd/main.go, testcase/bank2/cmd/main.go, testcase/block-writer/cmd/main.go, testcase/ledger/cmd/main.go, testcase/list-append/cmd/main.go, testcase/ondup/cmd/main.go, testcase/pessimistic/cmd/deadlock-detector/main.go, testcase/pessimistic/cmd/pipelined-pessimistic-locking/main.go, testcase/pessimistic/cmd/txn-rand-pessimistic/main.go, testcase/pocket/cmd/tiflash-pocket/main.go, testcase/rawkv-linearizability/cmd/main.go, testcase/resolve-lock/cmd/resolve-lock/main.go, testcase/rw-register/cmd/main.go, testcase/sqllogictest/cmd/main.go, testcase/vbank/cmd/main.go
There are too many combinations even for running a single case binary, eg. test args, tidb versions. Currently we create a namespace for each test run, which may lead to too many namespaces.
This PR allow user to customize cluster-name by flag, so that we can run cases in same namespace.
Tests 
Code changes
Side effects
- None
- None
```release-note
NONE
```
=> *: allow to customize cluster-name by flag

cmd/cdc-bank/main.go, cmd/read-stress/main.go, pkg/scaffolds/template/testcase/cmd/main.go, testcase/example/cmd/main.go, testcase/pocket/cmd/abtest/main.go, testcase/pocket/cmd/binlog-pocket/main.go, testcase/pocket/cmd/cdc-pocket/main.go, testcase/pocket/cmd/dm-pocket/main.go, testcase/pocket/cmd/tiflash-abtest/main.go, testcase/pocket/cmd/tiflash-cdc/main.go, testcase/titan/cmd/main.go
Sorry, I just missed some cases in #388 .
Let those cases be aware of `-cluster-name` flag.
Tests 
Code changes
Side effects
- None
- None
```release-note
NONE
```
=> *: let rest cases use `-cluster-name` flag

pkg/test-infra/tests/client.go
Signed-off-by: Thearas <thearas850@gmail.com>
A test may fail at `TestClient.CreateNamespace` when using a low-privileged K8S user which lacks the permission to create a namespace, even if the namespace it needs already exists.
Skip creating or updating namespace if the namespace is already existed.
Tests 
Code changes
Side effects
- None
- None
```release-note
NONE
```
=> skip creating namespace when the namespace is existed

testcase/cross-region/pkg/util/util.go, testcase/cross-region/tso.go
The current `WaitUntil` is not long enough to wait for the allocator election to finish.
I adjust the `WaitOption` to make these `WaitUntil`s wait longer.
Tests 
- Unit test
- E2E test
```release-note
NONE
```
=> cross-region: adjust the WaitUntil function and its options

testcase/bank2/client.go
https://github.com/pingcap/tipocket/issues/383#issuecomment-821094927.
Ignore `Error 1105: redirect failed` when admin check table.
Tests
Code changes
Side effects
```release-note
NONE
```
=> fix false positive admin check table in bank2 again

testcase/cross-region/tso.go
Use different test logic for different TSOs.
* For the Global TSO test, we will request Local TSO twice before and after a Global TSO request and compare it with them.
* For the Local TSO test, we will compare it with the previous Global and Local TSO.
Tests 
- Unit test
- E2E test
```release-note
NONE
```
=> Use different test logic for different TSOs

tests/cdc-bank/bank.go
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x14b68f1]
goroutine 222 [running]:
sync.(*Mutex).Lock(...)
/usr/local/go/src/sync/mutex.go:74
database/sql.(*DB).conn(0x0, 0x1b66040, 0xc00005c030, 0xc000696001, 0x7f33a848d008, 0xc000630000, 0x0)
/usr/local/go/src/database/sql/sql.go:1132 +0x41
database/sql.(*DB).exec(0x0, 0x1b66040, 0xc00005c030, 0x18f0c35, 0x8, 0x0, 0x0, 0x0, 0x1, 0x14c4130, ...)
/usr/local/go/src/database/sql/sql.go:1495 +0x66
database/sql.(*DB).ExecContext(0x0, 0x1b66040, 0xc00005c030, 0x18f0c35, 0x8, 0x0, 0x0, 0x0, 0x0, 0x14004e5860, ...)
/usr/local/go/src/database/sql/sql.go:1477 +0xde
database/sql.(*DB).Exec(...) …
```
=> cdc-bank: fix panic caused by nil pointer

testcase/cross-region/cmd/main.go, testcase/cross-region/cross-region.go, testcase/cross-region/go.sum, testcase/cross-region/tso.go
Currently, there are many test failures that are caused by timeouts due to resource constraints. To improve test success rate and focus on the TSO consistency check, we need to handle this situation.
- Only fail the cross-region test if a critical error occurs.
- Wait for leader election without any timeout.
Tests 
- Unit test
- E2E test
```release-note
NONE
```
=> cross-region: only fail the test if a critical error occurs

testcase/cross-region/tso.go
```
[2021/06/21 06:32:29.524 +00:00] [INFO] [tso.go:426] ["Wait for allocator election"] [name=cross-region-chaos-1624256277-dc-2-pd-1] [dc-location=cross-region-chaos-1624256277-dc-2]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x16c93f8]
goroutine 689 [running]:
github.com/pingcap/tipocket/testcase/cross-region.(*crossRegionClient).waitAllocator(0xc000820600, 0xc000a36c30, 0x27, 0xc00025e5a0, 0x22, 0x0, 0x0)
/src/testcase/cross-region/tso.go:433 +0x338
github.com/pingcap/tipocket/testcase/cross-region.(*crossRegionClient).transferPDAllocator(0xc000820600, 0xc00025e5a0, 0x22, 0x0, 0x0)
/src/testcase/cross-region/tso.go:354 +0x754 …
```
=> cross-region: fix the potential panic bug

testcase/bank2/client.go
tidb sometimes return error 1105 without message, just ignore it.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> bank2: ignore error 1105 without message

testcase/bank2/client.go
tidb sometimes return error 1105 with message：context deadline exceeded, just ignore it.
2021/07/21 18:06:33 client.go:398: [fatal] [bank2] ADMIN CHECK TABLE bank2_accounts fails: Error 1105: context deadline exceeded
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
NONE
=> bank2: ignore error 1105 with message:context deadline exceeded

testcase/bank2/client.go
`admin check table` may fail with `Error 1105: rpc error: code = Unknown desc = raft: stopped`, it's expected if pd nemeses are introduced.
Add such an error to the whitelist.
Tests 
Code changes
Side effects
- None
- None
```release-note
NONE
```
=> bank2: ignore `raft: stopped` when doing admin check table

testcase/resolve-lock/cmd/resolve-lock/main.go, testcase/resolve-lock/go.mod, testcase/resolve-lock/go.sum, testcase/resolve-lock/resolve_lock.go
the testcase return error message as follow，because nemesis：pd-scheduler random-merge-scheduler
2021/09/07 05:23:35 pd_scheduler.go:59: [info] apply nemesis pd-scheduler random-merge-scheduler on ns tipocket-debug-nrrdr
2021/09/07 05:23:35 pd_scheduler.go:63: [info] add scheduler random-merge-scheduler successfully
2021/09/07 05:27:34 resolve_lock.go:233: [error] [round-35] failed to run GC at safe point 427552777833021443
2021/09/07 05:27:34 resolve_lock.go:194: [info] test end 
2021/09/07 05:27:34 control.go:285: [fatal] run client error, GET request "http://debug-tidb.tipocket-debug-nrrdr.svc:10080/test/gc/resolvelock?safepoint=427552777833021443&physical=false", got 400 resolveLocks failed: region unavailable
none
Tests 
- Unit test
- E2E test
- Manual test (add detailed scripts or …
=> do not fail if resolve lock returns region unavailable

testcase/resolve-lock/resolve_lock.go
Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>
1. Add the error stack to distinguish the failure cause easily.
2. Don't keep running the test if PD is down.
=> add error stack for resolve-lock test

testcase/resolve-lock/resolve_lock.go
Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>
PD client wraps the raw error so that the error comparison fails. https://github.com/tikv/pd/blob/1db2398d1a508a1679ef51f5e06133cc821becbd/client/client.go#L949
=> fix comparing getTS error

testcase/resolve-lock/resolve_lock.go
test case failed because of getTS timeout：
```
[2021/12/04 04:23:17.849 +00:00] [ERROR] [client.go:259] ["[pd] getTS error"] [error="rpc error: code = Canceled desc = context canceled"] [errorVerbose="rpc error: code = Canceled desc = context canceled\ngithub.com/pingcap/pd/v4/client.(*client).processTSORequests\n\t/go/pkg/mod/github.com/pingcap/pd/v4@v4.0.0-beta.1.0.20200305072537-61d9f9cc35d3/client/client.go:295\ngithub.com/pingcap/pd/v4/client.(*client).tsLoop\n\t/go/pkg/mod/github.com/pingcap/pd/v4@v4.0.0-beta.1.0.20200305072537-61d9f9cc35d3/client/client.go:244\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"] [stack="github.com/pingcap/log.Error\n\t/go/pkg/mod/github.com/pingcap/log@v0.0.0-20200511115504-543df19646ad/global.go:42\ngithub.com/pingcap/pd/v4/client.(*clie …
```
=> ignore error:context canceled because of network delay

testcase/stale-read/client.go, testcase/stale-read/go.mod, testcase/stale-read/go.sum
Signed-off-by: linning <linningde25@gmail.com>
When read request met error, the connection will be closed and incoming requests sent with the connection will be failed too
Backoff and establish a new connection for incoming requests
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> stale read: reconnect when read request met errors

run/workflow/stale-read.jsonnet, testcase/stale-read/client.go
When establishing a new connection, the old one is not closed. Also, the connection used for background updating is not re-establish when met error.
Close the old connection and re-establish the connection for the background updating job. This PR also removes some network nemeses that may cause the connection of TiDB to become invalid.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> stale-read: fix connection error

pkg/test-infra/clusters.go, pkg/test-infra/tidb/recommend.go, pkg/test-infra/util/util.go
Since tidb-operator v1.3.0 the image field of tidbCluster component is deprecated actually and should replace it with baseImage + version to set the component image after that.
Ref: https://github.com/pingcap/tidb-operator/pull/4151
Tests 
Code changes
Side effects
```release-note
NONE
```
=> support tidb-operator v1.3.0

pkg/test-infra/clusters.go, pkg/test-infra/tidb/recommend.go, pkg/test-infra/util/util.go
This PR resolves the issue: `2022/04/11 12:00:18 suit.go:84: [fatal] deploy a cluster failed, maybe has no enough resources, err: admission webhook "[validating.admission.tidb.pingcap.com](http://validating.admission.tidb.pingcap.com/)" denied the request: spec.version: Invalid value: "": version must not be empty`
Set the version field using the version part of tidb image.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> fix: empty version validation failure after deploy tidb-operator webhook component
