pingcap/tipocket

test-infra/pkg/cdc/operation.go, test-infra/pkg/mysql/operation.go, test-infra/pkg/tidb/operation.go, test-infra/pkg/tidb/template.go, test-infra/tests/cdc/cdc.go
Signed-off-by: Aylei <rayingecho@gmail.com>
=> Fix cdc IT

.gitignore, pocket/core/core.go, pocket/main.go
Signed-off-by: cwen0 <cwenyin0@gmail.com> 
add duration time to run pocket，so we can set a finish time for this test
=> pocket: add duration time for test

test-infra/go.mod, test-infra/go.sum, test-infra/pkg/cdc/operation.go, test-infra/pkg/fixture/fixture.go, test-infra/pkg/mysql/operation.go, test-infra/pkg/tidb/operation.go, test-infra/run-test.sh, test-infra/tests/binlog/binlog.go, test-infra/tests/cdc/cdc.go, test-infra/tests/e2e_test.go
* add cdc-cli sync job
* make workload runnable
=> Make cdc workload runnable

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/question.md, .github/pull_request_template.md
=> add issue and pr template

Makefile, pkg/go-sqlsmith/README.md, pkg/nemesis/generator.go, pkg/pocket/Makefile, test-infra/go.mod, test-infra/tests/cdc/cdc.go
Signed-off-by: mapleFU <1506118561@qq.com>
Rename some imports.
Nothing changed
Tests 
- No code
Code changes
Side effects
```release-note
NONE
```
=> Rename some pkg.

.gitignore, cmd/tidb/main.go, cmd/util/suit.go, db/tidb/bank.go, db/tidb/long_fork.go, pkg/cluster/cluster.go, pkg/cluster/k8s.go, pkg/control/config.go, pkg/control/control.go, pkg/core/client.go, pkg/test-infra/pkg/control/control.go
Tests 
- Manual test
Code changes
```release-note
NONE
```
=> cases: make bank workload runnable with k8s

cmd/util/suit.go, pkg/nemesis/kill.go, pkg/nemesis/network_partition.go, pkg/nemesis/pod_kill.go
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> pkg/nemesis: Develop PodKill chaos supports

cmd/tidb/main.go, cmd/util/suit.go, db/tidb/bank.go, db/tidb/bank_service_quality.go, go.mod, go.sum, pkg/core/nemesis.go, pkg/nemesis/container_kill.go, pkg/nemesis/kill.go, pkg/nemesis/nemesis.go, pkg/nemesis/pod_kill.go
Add container kill support, that can be used on short-term node killing case.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> Add container kill support

Dockerfile, jobs/bank.yaml, jobs/bank_1.yaml, jobs/bank_sqt_1.yaml
close #42 
After #45 was merged, I will add more job cases.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> Add Dockerfile and k8s job support

Dockerfile, jobs/bank_1.yaml, jobs/bank_sqt_1.yaml
Minify Dockerfile
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> minify Dockerfile

Makefile, cmd/ledger/main.go, pkg/control/control.go, tests/ledger/ledger.go, util/error.go, util/util.go
close #56 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> Migrate schrodinger/transaction/ledger

go.sum, pkg/cluster/k8s.go, pkg/test-infra/binlog/recommander.go, pkg/test-infra/tests/client.go
Add a namespace check.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> chore: Create the specified namespace if not exist

cmd/tidb/main.go, db/tidb/admin_check.go, go.sum, pkg/check/admin-check/admin_check.go, pkg/util/util.go
close #60 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> Migrate schrodinger/check/admin_check 

Makefile, cmd/ledger/main.go, cmd/on-dup/main.go, pkg/control/control.go, tests/ondup/ondup.go, util/error.go
close #65 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> Migrate Schrodinger/logic/on_dup

cmd/util/suit.go, pkg/core/nemesis.go, pkg/nemesis/nemesis.go, pkg/nemesis/scaling.go
add a new nemesis
Periodic scale up and down with tidy-operator
Tests 
- No code
Code changes
Side effects
```release-note
NONE
```
=> add nemesis: scaling

Dockerfile, Makefile
Support run cases on GKE.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> *: support GKE

Makefile, cmd/deadlock-detector/main.go, cmd/util/suit.go, go.mod, pkg/core/nemesis.go, pkg/nemesis/leader_shuffle.go, pkg/nemesis/nemesis.go, pkg/nemesis/pd_scheduler.go, pkg/util/http/client.go, pkg/util/pdutil/client.go, tests/pessimistic/deadlock/deadlock.go, tests/pessimistic/deadlock/leader_change.go, tests/pessimistic/deadlock/single_statement_rollback.go
Migrate deadlock_detector case
Fixes https://github.com/pingcap/tipocket/issues/59
Replace pd-ctl with pd http api.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> Migrate deadlock_detector case

Makefile, cmd/bank2/main.go, tests/bank2/bank2.go
Fixes #53 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> Port from bank2 case

pkg/cluster/k8s.go, pkg/test-infra/tidb/operation.go
Fixes #92 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> support to load tidb cluster from available cluster

Makefile, cmd/abtest/main.go, cmd/bank2/main.go, cmd/pocket/main.go, go.mod, go.sum, pkg/cluster/k8s.go, pkg/pocket/config/config.go, pkg/pocket/creator/creator.go, pkg/test-infra/abtest/operation.go, pkg/test-infra/abtest/recommand.go, pkg/test-infra/fixture/abtest.go, pkg/test-infra/fixture/fixture.go, pkg/test-infra/tests/client.go
This PR enable abtest and add k8s provider for double cluster.
=> Support ABTest cluster provider and a ABTest case

argo/README.md, argo/template/abtest.yaml, argo/template/bank.yaml, argo/template/block-writer.yaml, argo/template/ledger.yaml, argo/template/region-available.yaml, argo/template/sqllogic.yaml, argo/template/tpcc.yaml, argo/template/txn-rand-pessimistic.yaml, argo/workflow/abtest.yaml, argo/workflow/bank.yaml, argo/workflow/block-writer.yaml, argo/workflow/ledger.yaml, argo/workflow/region-available.yaml, argo/workflow/sqllogic.yaml, argo/workflow/tpcc.yaml, argo/workflow/txn-rand-pessimistic.yaml
1. Add a readme for argo
2. update templates
3. add workflows manifests
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> Update argo manifests

go.sum, pkg/pocket/connection/connection.go, pkg/pocket/core/prepare.go, pkg/pocket/executor/executor.go, pkg/pocket/pkg/logger/logger.go
ABTest will fail by inconsistency, I guess it is due to setting global variables required some seconds to take effect. This PR fix this problem by waiting 10 seconds after setting up during database client init.
=> abtest: fix inconsistency

Dockerfile
Signed-off-by: Illyrix <Illyrix@outlook.com>
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> change configmap path

go.sum, pkg/pocket/connection/schema.go
Fix a bug when there are unknown numbers when fetch indexes from schema.
Change a function but the signature has no change.
Tests 
- Manual test
Code changes
Side effects
- No
- No
=> pocket: fix get indexes issue

configmap/pd.default.toml, configmap/pd.performance.toml, configmap/tidb.performance.toml, configmap/tikv.default.toml, configmap/tikv.performance.toml
Add some config files which will be used by different config in abtest.
=> config: add some example configs

argo/README.md, argo/template/abtest.yaml, argo/workflow/abtest.yaml, configmap/tidb/enable-chunk-rpc-false.toml, configmap/tidb/enable-chunk-rpc.toml, configmap/tidb/oom-use-tmp-storage-false.toml, configmap/tidb/oom-use-tmp-storage.toml, configmap/tidb/prepared-plan-cache-false.toml, configmap/tidb/prepared-plan-cache.toml
* enable-chunk-rpc
* oom-use-tmp-storage
* prepared-plan-cache
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> a/b test: more a/b test configs

pkg/pocket/core/lock_watcher.go
In SQL sequential execution, some work will be locked by other transactions. When meeting this situation, the lock watcher will count down some seconds and trigger a transaction commit or rollback for other transactions. The previous lock resolve for transactions are parallel and disorder, it will make some inconsistency in a/b test.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> a/b test: fix disorder when resolve lock

argo/workflow/abtest-chunk-rpc.yaml, argo/workflow/abtest-plan-cache.yaml, argo/workflow/abtest-tmp-storage.yaml
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> upload a/b test workflow files

pkg/control/control.go
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> Don't panic when no space left in tikv

argo/template/abtest.yaml, argo/template/binlog.yaml, argo/workflow/binlog.yaml
Add binlog template and workflow
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> argo: add binlog template and workflow

argo/template/bank-iochaos.yaml, argo/template/export-logs.yaml, argo/workflow/abtest-chunk-rpc.yaml, argo/workflow/abtest-plan-cache.yaml, argo/workflow/abtest-tmp-storage.yaml, argo/workflow/abtest.yaml, argo/workflow/bank-iochaos.yaml, argo/workflow/bank.yaml, argo/workflow/binlog.yaml, argo/workflow/block-writer.yaml, argo/workflow/ledger.yaml, argo/workflow/region-available.yaml, argo/workflow/sqllogic.yaml, argo/workflow/tpcc.yaml, argo/workflow/txn-rand-pessimistic.yaml
1. export loki logs to minio at the end of each case
2. add a bank iochaos template and workflow
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> export loki logs to minio at the end of each case

cmd/tpcc/main.go, db/tidb/bank.go, db/tidb/tpcc.go, tests/bank/bank.go, tests/bank2/bank2.go, tests/ledger/ledger.go, tests/region-available/region_available_detector.go
Some of case may fail when they occur dirty data on databases. so I add `truncate table` or `DROP table if exists` on `SetUp`
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> make case reentrant

pkg/cluster/k8s.go, pkg/test-infra/fixture/fixture.go, pkg/test-infra/tidb/recommend.go
Specify the number of tikv
add "tikv-rep"
Tests 
- No code
Code changes
Side effects
- NO
- NO
```release-note
NONE
```
=> add tikv-rep

argo/template/export-logs.yaml, argo/workflow/abtest-chunk-rpc.yaml, argo/workflow/abtest-plan-cache.yaml, argo/workflow/abtest-tmp-storage.yaml, argo/workflow/abtest.yaml, argo/workflow/bank-iochaos.yaml, argo/workflow/bank.yaml, argo/workflow/binlog.yaml, argo/workflow/block-writer.yaml, argo/workflow/ledger.yaml, argo/workflow/region-available.yaml, argo/workflow/sqllogic.yaml, argo/workflow/tpcc.yaml, argo/workflow/txn-rand-pessimistic.yaml
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> test 4.0 rc

pkg/test-infra/tidb/recommend.go
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> Use PullAlways ImagePullPolicy when creating TiDBCluster

cmd/sqllogic/main.go
Seems we forget to pass the `taskCount` to the case
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> fix sqllogic task count

pkg/cluster/k8s.go
We should tearn down cdc cluster after it finishes
=> Teardown cdc cluster

argo/template/abtest.yaml, argo/workflow/abtest-chunk-rpc.yaml, argo/workflow/abtest-plan-cache.yaml, argo/workflow/abtest-tmp-storage.yaml, argo/workflow/abtest.yaml, cmd/abtest/main.go, cmd/pocket/main.go, pkg/pocket/pkg/mysql/mysql.go, pkg/test-infra/fixture/abtest.go, pkg/test-infra/fixture/fixture.go
Add general log option.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> abtest: add general log option

pkg/control/control.go
Tipocket should fatal when it occurred an error throw by client.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> control: fatal when client starts failed

argo/workflow/abtest-chunk-rpc.yaml, argo/workflow/abtest-plan-cache.yaml, argo/workflow/abtest-tmp-storage.yaml, argo/workflow/abtest.yaml, go.sum, pkg/test-infra/fixture/fixture.go, pkg/test-infra/tidb/recommend.go
By now, the resources limit is too low for TiDB cluster. This PR increase the resouces limit 
Tests 
Code changes
Side effects
=> k8s: increase resouce limit

argo/template/tiflash.yaml, argo/workflow/tiflash.yaml
Please merge this after https://github.com/pingcap/tipocket/pull/143 get merged
=> Add tiflash argo workflow

pkg/pocket/core/check.go
The lock is not resolved in binlog test.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> fix incorrect lock

argo/workflow/bank-iochaos.yaml, argo/workflow/binlog.yaml, argo/workflow/cdc.yaml, argo/workflow/tpcc.yaml, cmd/util/suit.go, pkg/cluster/k8s.go, pkg/nemesis/container_kill.go, pkg/nemesis/iochaos.go, pkg/nemesis/kill.go, pkg/test-infra/tiflash/template.go
Add several nemesis for tiflash.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> Add tiflash nemesis

pkg/cluster/k8s.go, pkg/pocket/connection/exec.go, pkg/pocket/connection/log.go, pkg/pocket/executor/abtest.go, pkg/pocket/executor/single.go, pkg/pocket/util/util.go
For insert/update/delete statements, add affected rows in connection log, and will compare if the affected rows are same.
Tests 
Code changes
Side effects
- No
- No
=> abtest: add affected rows log

pkg/test-infra/tidb/recommend.go
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> Limit resource usage

argo/template/abtest.yaml, argo/template/binlog.yaml, argo/template/cdc.yaml
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> fix invalid flag

argo/template/abtest.yaml, argo/template/bank.yaml, argo/template/binlog.yaml, argo/template/block-writer.yaml, argo/template/cdc.yaml, argo/template/ledger.yaml, argo/template/read-stress.yaml, argo/template/region-available.yaml, argo/template/sc_bank.yaml, argo/template/sc_bank2.yaml, argo/template/sqllogic.yaml, argo/template/tiflash.yaml, argo/template/tpcc.yaml, argo/template/txn-rand-pessimistic.yaml, argo/template/vbank.yaml, argo/workflow/read-stress-unify-all.yaml, argo/workflow/vbank.yaml, cmd/bank2/main.go
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> argo: add repository field on template

pkg/cluster/types/cluster.go
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> Update clientNode string

tests/vbank/v_bank.go
Fix check invalid
If read operation is not OK, return true
=> fix v_bank Step method

pkg/test-infra/fixture/fixture.go
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> Bug fix: add component image version into fixture

pkg/test-infra/cdc/recommend.go
Fix #182
Already tested locally
=> Add cdc log container

pkg/elle/core/core.go
Signed-off-by: mapleFU <1506118561@qq.com>
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> Add some codes for explainer

pkg/nemesis/time_chaos.go
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> timechaos: fix generate bug

pkg/elle/core/consistency_model.go, pkg/elle/core/core.go, pkg/elle/core/graph.go, pkg/elle/txn/cycle.go, pkg/elle/txn/helper_fn.go, pkg/elle/txn/txn.go, pkg/elle/txn/txn_test.go, pkg/elle/txn/wr_txn.go
Signed-off-by: mapleFU <1506118561@qq.com>
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> Add code and test for txn

pkg/test-infra/tidb/recommend.go
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> tidb_cluster: use UTC timezone

pkg/elle/core/core.go, pkg/elle/core/core_test.go, pkg/elle/core/graph.go, pkg/elle/core/history.go, pkg/elle/core/history_test.go
Implement elle's core module.
Tests 
- Unit test
Code changes
=> Implement elle core

argo/workflow/tiflash-abtest.yaml, argo/workflow/tiflash-cdc.yaml, argo/workflow/tiflash.yaml
=> Add missed tiflash tag

pkg/elle/core/check.go, pkg/elle/core/core.go, pkg/elle/core/depend.go, pkg/elle/core/graph.go, pkg/elle/core/history.go, pkg/elle/txn/wr_txn.go
Signed-off-by: mapleFU <1506118561@qq.com>
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> ADD the basic interface of explainer

go.mod, pkg/elle/core/graph.go, pkg/elle/core/graph_test.go
update graph.go (FindCycle and FindCycleStartingWith)
update graph.go (FindCycle and FindCycleStartingWith)
Tests 
- Unit test
Code changes
Side effects
- NO
- NO
```release-note
NONE
```
=> update graph.go (FindCycle and FindCycleStartingWith)

pkg/test-infra/cdc/recommend.go, pkg/test-infra/fixture/cdc.go, pkg/test-infra/fixture/fixture.go
Add some startup parameter in cdc
- set `log-level` to debug
- set `tz` to UTC
Tests 
- Unit test
- E2E test
=> update cdc server startup parameter

argo/template/cdc.yaml, argo/workflow/cdc.yaml
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> update cdc workload

argo/cron/cdc-normal.yaml, argo/cron/cdc.yaml
=> Add cdc cron workflows

pkg/test-infra/cdc/recommend.go
Update CDC address
Tests 
Code changes
Side effects
No.
```release-note
NONE
```
=> cdc: update address and advertise address

cmd/follower-read/main.go
Signed-off-by: TXXT <hunterlxt@live.com>
- fix follower read cmd
=> fix follower read cmd

tests/follower/follower.go
In SplitRegion test case, unify the table name.
=> Fix test follower read bug

cmd/append/main.go, cmd/follower-read/main.go, cmd/util/suit.go, pkg/control/control.go, pkg/elle/core/history.go, pkg/elle/core/history_test.go, pkg/elle/list_append/list_append.go, pkg/elle/list_append/list_append_test.go, pkg/elle/list_append/utils.go, pkg/elle/txn/helper_fn.go, pkg/elle/txn/txn.go, pkg/elle/txn/wr_txn.go, pkg/elle/txn/wr_txn_test.go, tests/list_append/append.go
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> case: txn list_append

argo/cron/list-append.yaml, argo/template/list-append.yaml, tests/list_append/append.go
Fix nil pointer dereference panic
```log
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x505b1e6]
goroutine 16 [running]:
github.com/pingcap/tipocket/tests/list_append.convertOperationsToHistory(0xc0136b8000, 0x30d40, 0x30d40, 0x40d6766, 0x530bb80, 0xc00004c5a0)
/Users/manjunpeng/Workspaces/tipocket/tests/list_append/append.go:338 +0x3c6
github.com/pingcap/tipocket/tests/list_append.AppendChecker.Check(0x0, 0x0, 0xc0136b8000, 0x30d40, 0x30d40, 0x0, 0x0, 0x0)
/Users/manjunpeng/Workspaces/tipocket/tests/list_append/append.go:297 +0x5d
```
Tests 
- Unit test
- E2E test
- No code
Code changes
- Has Go code …
=> list_append: fix the fail response without value problem

argo/cron/list-append.yaml, argo/cron/sc_bank.yaml, argo/cron/sc_bank2.yaml
Fix minor bugs in cron workflows. Tested okay in the cluster.
=> remove duplicate loki config in cron

argo/workflow/titan-bank.yaml, config/tikv/titan-bank.toml
add a tikv config file which enable titan in bank workload
Tests 
- No code
Code changes
Side effects
=> add tikv config titan-bank.toml

pkg/control/control.go, pkg/nemesis/nemesis.go, pkg/nemesis/pd_scheduler.go, tests/list_append/append.go
Close #237 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> Fix: panic when random_kill is specified in local tests

.gitignore, argo/workflow/bank-tikv-encryption.yaml, argo/workflow/bank2-tikv-encryption.yaml, argo/workflow/tiflash-tikv-encryption.yaml, argo/workflow/tpcc-tikv-encryption.yaml, config/tikv/encryption.toml
Signed-off-by: Yi Wu <yiwu@pingcap.com>
Add workflow for tikv encryption test cases.
Tests 
Shall see how to run and see.
No.
```release-note
NONE
```
=> Add workflow for tikv encryption test cases

argo/template/sqllogic.yaml
Fix sqllogic case parameter
Signed-off-by: TXXT <hunterlxt@live.com>
=> Fix sqllogic case parameter

pkg/control/control.go
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> panic check: save panic-logs in logs

argo/template/sc_bank2.yaml, argo/template/sqllogic.yaml, argo/workflow/release/block-writer.yaml
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> Fix template error

cmd/dm-pocket/main.go, cmd/util/suit.go, go.mod, go.sum, pkg/nemesis/kill.go, pkg/pocket/creator/dm.go, pkg/test-infra/dm/operation.go
- TiDB may not catchup MySQL quickly
- need to add nemesis for DM
- decrease check duration from 1m to 10s
- add pod kill nemesis for DM
Tests 
- Unit test
Code changes
```release-note
NONE
```
=> dm: decrease check duration; add pod kill nemesis

pkg/control/control.go, pkg/core/nemesis.go
Fix a bug that nemesisGenerators stops generate nemesis when it reaches the end.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> control: dispatch nemesis continuously

cmd/dm-pocket/main.go
Tests 
- Unit test
- E2E test
- No code
Code changes
```release-note
NONE
```
=> dm: add nemesis generate delay

Dockerfile, argo/template/ledger.yaml, argo/template/sc_bank.yaml, argo/template/sc_bank2.yaml, pkg/control/goroutine_leak_check.go
We need to update eat.txt quite frequently. :(
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> leak_check: use the web eat resources

argo/cron/bank.yaml, argo/cron/cdc-kafka-normal.yaml, argo/cron/cdc-kafka.yaml, argo/cron/cdc-normal.yaml, argo/cron/cdc.yaml, argo/cron/ledger.yaml, argo/cron/list-append.yaml, argo/cron/rw-register.yaml, argo/cron/sc_bank.yaml, argo/cron/sc_bank2.yaml, argo/cron/vbank.yaml, argo/template/dm.yaml, argo/workflow/release/bank.yaml, argo/workflow/release/block-writer.yaml, argo/workflow/release/ledger.yaml, argo/workflow/release/list-append.yaml, argo/workflow/release/rawkv-linearizability.yaml, argo/workflow/release/region-available.yaml, argo/workflow/release/rw-register.yaml, argo/workflow/release/sc_bank.yaml, argo/workflow/release/sc_bank2.yaml, argo/workflow/release/tpcc.yaml, argo/workflow/release/txn-rand-pessimistic.yaml, argo/workflow/release/vbank.yaml, cmd/util/suit.go
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> Update argo release dir and fix log print issue

pkg/test-infra/fixture/fixture.go, pkg/test-infra/tidb/operation.go, pkg/test-infra/tidb/template.go
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> Support enable TiDB failpoints

pkg/pocket/core/check.go, pkg/pocket/core/core.go
close #284 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> Reduce the false-positive cases of pocket test

argo/template/sc_bank.yaml, argo/workflow/release/bank.yaml, argo/workflow/release/block-writer.yaml, argo/workflow/release/ledger.yaml, argo/workflow/release/list-append.yaml, argo/workflow/release/rawkv-linearizability.yaml, argo/workflow/release/region-available.yaml, argo/workflow/release/rw-register.yaml, argo/workflow/release/sc_bank.yaml, argo/workflow/release/sc_bank2.yaml, argo/workflow/release/sqllogic.yaml, argo/workflow/release/tpcc.yaml, argo/workflow/release/txn-rand-pessimistic.yaml, argo/workflow/release/vbank.yaml, pkg/control/goroutine_leak_check.go, pkg/test-infra/fixture/fixture.go
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> Mute leak check

argo/workflow/release/list-append.yaml
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> update image version to release-4.0-failpoint

argo/template/rawkv-linearizability.yaml, pkg/test-infra/cdc/recommend.go
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> Fix: add advertise-addr for cdc

argo/README.md
=> Fix argo/readme

config/tidb/new_collations_enabled_on_first_bootstrap.toml
Add `new_collations_enabled_on_first_bootstrap=true` for tidb config to run tests
Tests 
- No code
Code changes
Side effects
- No
- No
```release-note
NONE
```
=> add new_collations_enabled_on_first_bootstrap=true for tidb config

argo/cron/cdc-file-sort.yaml, argo/cron/cdc-kafka-normal.yaml, argo/cron/cdc-normal.yaml, argo/cron/cdc.yaml, argo/template/cdc.yaml, pkg/test-infra/cdc/recommend.go, pkg/test-infra/fixture/cdc.go, pkg/test-infra/fixture/fixture.go
Support test file sort in CDC
- Add two options, `cdc_sort-engine` and `cdc_sort-dir`
- Add one cron workflow template `argo/cron/cdc-file-sort.yaml` (will this cron be deployed in ticpket automatically?)
Tests 
- Unit test
- E2E test
- release-note
NONE
=> add file sort option in cdc case

cmd/cdc-pocket/main.go
=> Add delay before the first nemesis

pkg/control/control.go
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> control: turn up the wait condition duration of dumping state

pkg/cluster/manager/apiserver/artifact.go, pkg/cluster/manager/apiserver/workload.go, pkg/cluster/manager/artifacts/monitor.go, pkg/cluster/manager/deploy/tiup.go, pkg/cluster/manager/types/workload.go, pkg/cluster/manager/util/docker.go, pkg/cluster/manager/workload/executor.go
This PR uploads workload artifacts(if exist) to S3.
Besides, it also changes the artifact storage path to $cluster_id/$uuid
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> Apiserver: archive workload artifacts

pkg/cluster/manager/deploy/tiup.go
Fix a bug that still patches tikv when no tikv instance is installed
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> Apiserver: ignore patch when no instance is installed

pkg/cluster/manager/apiserver/artifact.go, pkg/cluster/manager/apiserver/workload.go, pkg/cluster/manager/artifacts/monitor.go, pkg/cluster/manager/util/docker.go, pkg/cluster/manager/workload/executor.go
This PR archives container stdout logs
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> Apiserver: archive container stdout logs

cmd/cluster/Dockerfile, cmd/cluster/mock_workload.sh, cmd/cluster/test.sh, pkg/cluster/manager/apiserver/cluster.go, pkg/cluster/manager/apiserver/manager.go, pkg/cluster/manager/apiserver/workload.go, pkg/cluster/manager/deploy/tiup.go, pkg/cluster/manager/types/cluster.go, pkg/cluster/manager/util/util.go, pkg/cluster/manager/workload/executor.go
Support the clean data API and add a test script.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> Apiserver: support the cluster clean data api

pkg/cluster/manager/apiserver/cluster.go, pkg/cluster/manager/apiserver/workload.go, pkg/cluster/manager/types/workload.go, pkg/cluster/manager/util/docker.go, pkg/cluster/manager/workload/executor.go
Support a new workload that import data to TiDB
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> Apiserver: support importer workload

pkg/cluster/manager/apiserver/cluster.go, pkg/cluster/manager/apiserver/manager.go, pkg/cluster/manager/apiserver/resource.go, pkg/cluster/manager/apiserver/workload.go, pkg/cluster/manager/service/resource.go, pkg/cluster/manager/types/resource.go, pkg/cluster/manager/workload/executor.go
Support to specify a static resource id when requesting resources.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> Apiserver: support static resource request

argo/cron/async-bank2.yaml, argo/template/sc_bank2.yaml, config/tidb/enable-async-commit.toml
Add a config file to run async commit tests
Tests 
- No code
Code changes
Side effects
```release-note
NONE
```
=> Add an async commit config

argo/cron/async-tpcc.yaml, argo/template/tpcc.yaml
Add a TPC-C workflow with async commit enabled
Tests 
- No code
Code changes
Side effects
```release-note
NONE
```
=> Add a cron workflow to run TPC-C with async commit enabled

argo/template/sc_bank2.yaml, tests/ledger/ledger.go
fix multiple statements error
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> case: fix multiple statements error

tests/resolve-lock/resolve_lock.go
Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>
Now the resolve_lock test always fails when the test is finished.
Replace the provided context with a background context.
Tests 
```release-note
NONE
```
=> shutdown resolve_lock test gracefully

Makefile, cmd/backup/main.go, go.mod, go.sum, tests/backup/backup.go
Add a test case for working with br.
Originaly this case is for testing:
When the calculated commit ts after the successful prewrite of the async commit transaction is the same as the last backup ts, The next incremental backup should contain the data submitted by the transaction.
But in the future we can add more br related things here. 
Add a test case with using br via `BACKUP` and `RESTORE` sql, to check whether the incremental backup work as expected.
Most of the sql are adopt from `bank2`, with backup and restore added.
Tests 
- E2E test
Code changes
```release-note
Add a test case for br, ie. bin/backup
```
=> Add test case with br

argo/template/resolve-lock.yaml, cmd/resolve-lock/main.go, config/pd.schedule-region.toml, config/tikv/split-on-table.toml, pkg/util/http/client.go, tests/resolve-lock/resolve_lock.go
scheduling
Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>
* Fix a concurrency bug of writing locks: the `mockLockTs` is not thread-safe.
* Add more logs for debugging.
* Add config files for cases involving region schedule.
Tests 
Code changes
```release-note
NONE
```
=> fix some bugs of resolve-lock test & add config files for region schedule

README.md
broken link
update the line
Tests 
- No code
Code changes
Side effects
```release-note
NONE
```
=> fix go-sqlsmith broken link

README.md, pkg/cluster/cluster.go, pkg/test-infra/dm/operation.go, pkg/test-infra/mysql/operation.go, pkg/test-infra/tidb/operation.go, pkg/test-infra/tidb/recommend.go, pkg/test-infra/util/util.go
This PR uses the `hostname.subdomain.namespace.svc` format node ip
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> chore: uses the `hostname.subdomain.namespace.svc` format node ip

pkg/cluster/cluster.go
Signed-off-by: xhe <xw897002528@gmail.com>
I did not see a good output when I am logging. I do not even know the type(component) of the node.
Tests 
- Unit test
- E2E test
Code changes
```release-note
NONE
```
=> *: better print for node&client node

pkg/test-infra/binlog/operation.go, pkg/test-infra/cdc/operation.go, pkg/test-infra/dm/operation.go, pkg/test-infra/mysql/operation.go, pkg/test-infra/tidb/operation.go, pkg/test-infra/util/util.go, testcase/rawkv-linearizability/cmd/main.go
https://github.com/pingcap/tipocket/issues/364#issuecomment-782551725
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> control: uses fqdn as node ip

tests/cdc-bank/bank.go
Print more information in `cdc-bank` to help diagnosis.
```release-note
NONE
```
=> some cdc-bank improvements

tests/bank2/bank2.go
Signed-off-by: Yilin Chen <sticnarf@gmail.com>
Closes https://github.com/pingcap/tipocket/issues/383.
Filter errors that are unrelated to consistency when checking the result of admin check table.
```release-note
NONE
```
=> fix false positive admin check table in bank2

Makefile
Add the `cross-region` test to `Makefile`.
Update the TiPocket `Makefile`.
Tests 
- Unit test
- E2E test
```release-note
NONE
```
=> Add the cross-region test to Makefile

testcase/cross-region/cmd/main.go
Signed-off-by: Thearas <thearas850@gmail.com>
The testcase cross-region has several hard-coded values like namespace and storage-class, which makes it impossible to have another value.
Remove those hard-coded values and let them be the default values of their corresponding flags, so we can assign values through the command line.
Tests 
Code changes
Side effects
```release-note
NONE
```
=> set default flag value for cross-region

pkg/control/goroutine_leak_check.go
Fix the "open tipocket-logs/leak-check: no such file or directory" issue
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
None
```release-note
NONE
```
=> Fix "open tipocket-logs/leak-check: no such file or directory" issue

doc/command_line_chaos.md
The logo was not displayed because the URL was wrong. 
Use the GitHub raw content URI to fix it.
Tests 
- No code
Code changes
- None
Side effects
- None
- None
```release-note
NONE
```
=> Fix logo ref in CLI doc

pkg/test-infra/fixture/fixture.go, run/lib/case.libsonnet
close #399 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> fixture: update default tikv-config

testcase/cross-region/cmd/main.go, testcase/cross-region/cross-region.go, testcase/cross-region/pkg/util/util.go, testcase/cross-region/tso.go
Refine the `cross-region` test.
* Make the test run multiple times.
* Add the last Global TSO check.
* Make the wait time longer.
Tests 
- Unit test
- E2E test
```release-note
NONE
```
=> Refine the cross-region test

testcase/cross-region/cmd/main.go
Signed-off-by: JmPotato <ghzpotato@gmail.com>### What problem does this PR solve? 
Redefine round flag to avoid the conflict.
Tests 
- Unit test
- E2E test
```release-note
NONE
```
=> Redefine round flag to avoid the conflict

testcase/cross-region/cmd/main.go
Some default flag values of cross-region is puzzling, so we delete it.
Delete the default value of these 5 flags.
Tests 
Code changes
Side effects
```release-note
NONE
```
=> remove some default flag values of cross-region

go.mod, tests/cdc-bank/bank.go
Since TiCDC is built on the eventual consistency model,  cdc-bank test case may failed due to sync latency, try to fix it.
Tests 
- No code
Code changes
Side effects
NONE
=> fix cdc-bank eventual consistency issue.

.github/workflows/build.yaml, .github/workflows/build_workflow.yaml, .github/workflows/precheck.yaml, .github/workflows/test.yaml, Dockerfile, Makefile, go.mod, logsearch/go.sum, pkg/scaffolds/template/testcase/go.module.go, testcase/bank/go.mod, testcase/bank2/go.mod, testcase/block-writer/go.mod, testcase/cross-region/go.mod, testcase/example/go.mod, testcase/example/go.sum, testcase/ledger/go.mod, testcase/list-append/go.mod, testcase/ondup/go.mod, testcase/pessimistic/go.mod, testcase/pocket/go.mod, testcase/rawkv-linearizability/go.mod, testcase/resolve-lock/go.mod, testcase/rw-register/go.mod, testcase/sqllogictest/go.mod, testcase/titan/go.mod, testcase/ttl/go.mod, testcase/vbank/go.mod, testcase/verifier/go.mod
Upgrade go version to 1.16  https://github.com/pingcap/tipocket/issues/412?from=from_parent_mindnote
change go mod version and base image
Tests 
Code changes
- Has Makefile code change
- Has Dockerfile code change
```release-note
NONE
```
=> Upgrade go version to 1.16 for issue #412

tests/cdc-bank/bank.go
fix end time might be null for create table ddl.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> cdc-bank: fix end time might be null issue.

pkg/test-infra/tidb/recommend.go
This PR decreases the CPU/memory resource requests
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> chore: decrease the cpu/memory resource requests

cmd/crud/main.go, pkg/test-infra/fixture/fixture.go, pkg/test-infra/tidb/recommend.go, testcase/bank/client.go, testcase/bank/cmd/main.go, testcase/bank2/client.go, testcase/bank2/cmd/main.go, testcase/ledger/client.go, testcase/ledger/cmd/main.go, testcase/sqllogictest/client.go, testcase/sqllogictest/cmd/main.go, testcase/sqllogictest/pkg/util/util.go, testcase/sqllogictest/sqllogic.go, tests/cdc-bank/bank.go, tests/crud/crud.go, util/util.go
support test tiflash in case bank/bank2/crud/ledger/sqllogic
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> support test tiflash in case bank/bank2/crud/ledger/sqllogic

testcase/bank2/client.go
`admin check table fail with error :Error 1105: rpc error: code = Unknown desc = raft proposal dropped，it is expected when tikv nemeses injection`
`ignore the error code with this error message`
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> bank2：ignore error message: raft proposal dropped

pkg/test-infra/tidb/recommend.go
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> try to change tiflash log level to debug

testcase/cross-region/cross-region.go, testcase/cross-region/go.mod, testcase/cross-region/go.sum
Enable TSO Follower Proxy and set max TSO batch wait interval for the cross-region testcase.
Enable TSO Follower Proxy and set max TSO batch wait interval for the cross-region testcase.
Tests 
- Unit test
-->
```release-note
NONE
```
=> cross-region: enable TSO Follower Proxy and set max TSO batch wait interval

testcase/bank2/client.go
`admin check table fail with error ADMIN CHECK TABLE bank2_accounts fails: Error 1105: no available connections，it is expected when tikv nemeses injection`
`ignore the error code with this error message`
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
=> ignore err msg:no available connections

testcase/pessimistic/pkg/pipeline/pipeline.go
With in-memory pessimistic locks, the risk of immediate lock loss is low. But the loss risk is higher some while after the key is locked, because locks are transferred during region changes.
So, I add another mode that checks whether the lock exists in the next 500 milliseconds after locking. Hopefully this will test in-memory pessimistic locks better.
```release-note
NONE
```
=> Check some locks in a loop in pipelined-pessimistic-lock test

pkg/control/panic_check.go
If the following error code occurs, it means that the data is inconsistent and the test case fails
ref:https://github.com/pingcap/docs-cn/pull/7880/files
added error message matching when scanning logs
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
NONE
```
=> check inconsistency error code

testcase/bank2/client.go, testcase/bank2/cmd/main.go
add connection parameters to set assert = strict mode
the connection parameters can be set when the test case is executed
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
NONE
```
=> bank2 test case add conn parameter
